//Get current year, requried by some license text
function getYear() {
  let dt = new Date();
  return dt.getFullYear();
}

// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(gmLicense) {
  switch (gmLicense) {
    case 'Apache':
      return `![License Apache](https://img.shields.io/badge/License-Apache%202.0-yellowgreen.svg)`;
      break;
    case 'Boost':
      return `![License Boost](https://img.shields.io/badge/License-Boost%201.0-lightblue.svg)`;
      break;
    case 'BSD':
      return `![License BSD](https://img.shields.io/badge/License-BSD%203--Clause-orange.svg)`;
      break;
    case 'GNU_GPLv2':
      return `![License: GPL v2](https://img.shields.io/badge/License-GPL%20v2-blue.svg)`;
      break;
    case 'GNU_GPLv3':
      return `![License: GPL v3](https://img.shields.io/badge/License-GPLv3-blue.svg)`;
      break;
    case 'MIT':
      return `![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)`;
      break;
    case 'Unlicense':
      return `![License: Unlicense](https://img.shields.io/badge/license-Unlicense-blue.svg)`;
    default:
      return "";

  }
}

// TODO: Create a function that returns the license link
function renderLicenseLink(gmLicense) {
  switch(gmLicense) {
    case 'Apache':
      return `http://www.apache.org/licenses/LICENSE-2.0`;
      break;
      case 'Boost':
        return `https://www.boost.org/LICENSE_1_0.txt`;
        break;
      case 'BSD':
        return `https://opensource.org/licenses/BSD-3-Clause`;
        break;
      case 'GNU_GPLv2':
        return `https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html`;
        break;
      case 'GNU_GPLv3':
        return `https://www.gnu.org/licenses/gpl-3.0`;
        break;
      case 'MIT':
        return `https://opensource.org/licenses/MIT`;
        break;
      case 'Unlicense':
        return `http://unlicense.org/`;
      default:
        return "";
  }
}


// TODO: Create a function that returns the license section of README
//Note: requires specific formating for markdown, can not be realigned with 'readability spacing'
function renderLicenseSection(gmLicense, username) {

  const badge = renderLicenseBadge(gmLicense);
  const link = renderLicenseLink(gmLicense);
  const year = getYear();

  switch(gmLicense) {
    case 'Apache':
      return `  

## License  
   
### Apache  
${badge}  

Copyright ${year} ${username}  

Licensed under the Apache License, Version 2.0 (the "License");  
you may not use this file except in compliance with the License.  
You may obtain a copy of the License at  
  
${link}  
  
Unless required by applicable law or agreed to in writing, software  
distributed under the License is distributed on an "AS IS" BASIS,  
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  
See the License for the specific language governing permissions and  
limitations under the License.  
`;
      break;
    case 'Boost':
      return `## License  

### Boost License, Version 1.0
${badge}  
${link}  

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:  

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.  

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.  
  
`;
      break;
  case 'BSD':
      return `## License  
### BSD 3-Clause License
${badge}  

${link}  

Copyright (c) ${year}, ${username} 
All rights reserved.  

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:  

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.  

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.  

3. Neither the name of the copyright holder nor the names of its contributors
   may be used to endorse or promote products derived from this software without
   specific prior written permission.  

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.  

`;
    break;
  case 'GNU_GPLv2':
      return `## License
### GNU GPL v2  
${badge}  

${link}  

Copyright (c) ${year} ${username}  

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.  

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.  

`;
      break;
    case 'GNU_GPLv3':
      return `## License  
### GNU GPL v3 
${badge}  

${link}  

Copyright (c) ${year} ${username}  

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.  

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.  

`;
      break;
    case 'MIT':
      return `## License
### MIT License  
${badge}  

${link}  

The MIT License (MIT)  

Copyright (c) ${year} ${username}  

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:  

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.  

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.  

`;
      break;
      case 'Unlicense':
        return `## License  
### The Unlicense  

${badge}  

${link} 

This is free and unencumbered software released into the public domain.  

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.  

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.  

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.  

`;
    default:
      return `## License  
No license has been selected for this project.  
  
`; 
  }
}

//call with variable filename
function renderTitleSection(gmTitle) {
  return `  
# Project: ${gmTitle}  


`;
}

function renderBody(gmDescription, gmInstallation, gmUsage) {
  return `    
## Description  
${gmDescription}  


## Table of Contents
- [Installation](#installation)
- [Usage](#usage)
- [License](#license)
- [Contribution Guidelines](#contribution-guidelines)
- [Test Instructions](#test-instructions)
- [Questions](#questions)


## Installation  
${gmInstallation}  


## Usage  
${gmUsage}  


`;
}

function renderEndofDoc(gmContributing, gmTests, gmGithubName, gmEmail) {
  return `## Contribution Guidelines  
${gmContributing}  


## Test Instructions  
${gmTests}  



## Questions    
GitHub Name: ${gmGithubName}  
GitHub Profile: https://github.com/${gmGithubName}  
For questions regarding this project, please contact me by email at ${gmEmail}.  
Thank you for your intrest.  
`;
}

// TODO: Create a function to generate markdown for README
//combines sections into single markdown text block to be used to generate readme.md file
function generateMarkdown(fulln, filen, descr, inst, usg, licn, contr, tst, ghn, eml) {
  let markdownText = "";
  let titleSection = renderTitleSection(filen);
  let badgeSection = renderLicenseBadge(licn);
  let bodySection = renderBody(descr, inst, usg);
  let licenseSection = renderLicenseSection(licn, fulln);
  let endOfDocSection = renderEndofDoc(contr, tst, ghn, eml);

  markdownText = (titleSection + badgeSection + bodySection + licenseSection + endOfDocSection); 
  return markdownText; 
}

//export mode using generateMarkdown
module.exports = generateMarkdown;